"""Import every mapper so ``Base.metadata`` is complete before ``create_all``."""
from __future__ import annotations

from app.models.compute import (
    STATES_HOLDING_COMPUTE,
    STATES_HOLDING_DISK,
    Flavor,
    Hypervisor,
    Keypair,
    Server,
    ServerGroup,
)
from app.models.failure import VALID_ACTIONS, VALID_SERVICES, FailureInjection
from app.models.identity import (
    Endpoint,
    Project,
    Role,
    RoleAssignment,
    Service,
    Token,
    User,
)
from app.models.loadbalancer import (
    HealthMonitor,
    L7Policy,
    L7Rule,
    Listener,
    LoadBalancer,
    Member,
    Pool,
)
from app.models.network import (
    FloatingIP,
    Network,
    Port,
    Router,
    SecurityGroup,
    SecurityGroupRule,
    Subnet,
)
from app.models.objectstore import Container, ObjectMetadata, SwiftAccount
from app.models.quota import UNLIMITED, Quota
from app.models.storage import (
    VOLUME_STATES_HOLDING_DISK,
    Backup,
    Image,
    ImageMember,
    Snapshot,
    Task,
    Volume,
    VolumeAttachment,
    VolumeType,
)

__all__ = [
    "STATES_HOLDING_COMPUTE",
    "STATES_HOLDING_DISK",
    "VOLUME_STATES_HOLDING_DISK",
    "VALID_ACTIONS",
    "UNLIMITED",
    "VALID_SERVICES",
    "Backup",
    "Container",
    "Endpoint",
    "FailureInjection",
    "Flavor",
    "FloatingIP",
    "HealthMonitor",
    "Hypervisor",
    "Image",
    "ImageMember",
    "Keypair",
    "L7Policy",
    "L7Rule",
    "Listener",
    "LoadBalancer",
    "Member",
    "Network",
    "ObjectMetadata",
    "Pool",
    "Port",
    "Project",
    "Quota",
    "Role",
    "Router",
    "RoleAssignment",
    "SecurityGroup",
    "SecurityGroupRule",
    "Server",
    "ServerGroup",
    "Service",
    "Snapshot",
    "Subnet",
    "SwiftAccount",
    "Task",
    "Token",
    "User",
    "Volume",
    "VolumeAttachment",
    "VolumeType",
]
